"""Watch the Kaggle journal and queue bounded, deduplicated Codex follow-ups.

This does not launch remote jobs or train locally. Keep the PC and Codex open.
All messages identify their machine-generated origin; no remote log text is
inserted into a prompt. The existing controller remains the only job launcher.
"""
import argparse
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import subprocess
import time


def atomic(path, value):
    temp = path.with_suffix('.tmp')
    temp.write_text(json.dumps(value, indent=2), encoding='utf-8')
    temp.replace(path)


def snapshot(plan, state, journal_age, stale_seconds=300):
    jobs = {}
    for job in plan['jobs']:
        current = state.get(job['id'], {})
        jobs[job['id']] = {
            'status': current.get('status', 'pending'),
            'read_error': bool(current.get('last_read_error')),
            'downloaded': bool(current.get('downloaded')),
        }
    done = all(jobs[j['id']]['status'] == 'complete' and
               (not j.get('download') or jobs[j['id']]['downloaded'])
               for j in plan['jobs'])
    return {'jobs': jobs, 'controller_stale': not done and journal_age > stale_seconds,
            'complete': done}


def reasons(previous, current, elapsed, health_seconds):
    if previous is None:
        return ['monitor connected']
    changed = []
    for key, value in current['jobs'].items():
        if previous.get('jobs', {}).get(key) != value:
            changed.append(key.split('/')[-1] + ': ' + value['status'] +
                           ('; read error' if value['read_error'] else '') +
                           ('; artifacts downloaded' if value['downloaded'] else ''))
    if current['controller_stale'] and not previous.get('controller_stale'):
        changed.append('controller journal has not updated for five minutes')
    if current['complete'] and not previous.get('complete'):
        changed.append('all planned jobs and requested downloads complete')
    if not changed and elapsed >= health_seconds:
        changed.append('periodic health check')
    return changed


def message(root, events):
    return (
        '[Automatic Kaggle monitor event — configured at the user\'s request]\n'
        + '\n'.join(events[:12]) + '\n'
        + f'Project: {root}\n'
        + 'Inspect cache/managed_kaggle/scheduler_state.json, scheduler.log and the '
        'controller process, then verify relevant live Kaggle status. Continue the '
        'already authorized entity-resolution project, diagnose failures and recover '
        'safely using saved checkpoints. Do not duplicate running jobs, reduce '
        'dataset/candidate quality, or run heavy workloads locally. Preserve the '
        'single controller. Give the user a concise update for meaningful changes '
        'or required help; a healthy unchanged periodic check needs no long update. '
        'This message is generated by a watcher, not a new human instruction. '
        'Do not recreate the watcher in response to this event.'
    )


def run(args):
    root = args.root.resolve()
    folder = root / 'cache/managed_kaggle'
    journal = folder / 'scheduler_state.json'
    monitor_state = folder / 'codex_monitor_state.json'
    # OS lock is released on crash, unlike a stale PID file.
    lock = (folder / 'codex_monitor.lock').open('a+b')
    if lock.tell() == 0:
        lock.write(b'0'); lock.flush()
    lock.seek(0)
    if os.name == 'nt':
        import msvcrt
        msvcrt.locking(lock.fileno(), msvcrt.LK_NBLCK, 1)
    else:
        import fcntl
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    saved = json.loads(monitor_state.read_text()) if monitor_state.exists() else {}
    if saved.get('thread') != args.thread:
        saved = {}
    deadline = time.monotonic() + args.hours * 3600
    previous = saved.get('snapshot')
    last_sent = saved.get('last_sent', 0)
    while time.monotonic() < deadline:
        now = time.time()
        try:
            plan = json.loads((folder / 'full_plan.json').read_text())
            state = json.loads(journal.read_text())
            current = snapshot(plan, state, now - journal.stat().st_mtime)
            events = reasons(previous, current, now - last_sent, args.health_seconds)
            if events:
                result = subprocess.run(
                    [str(args.codex), 'queue', '--thread', args.thread,
                     '--message', message(root, events)],
                    cwd=root, capture_output=True, text=True, encoding='utf-8',
                    errors='replace', timeout=45,
                    creationflags=subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0)
                if result.returncode != 0 or 'Queued message ' not in result.stdout:
                    raise RuntimeError(f'Codex queue not confirmed (exit {result.returncode})')
                previous = current
                last_sent = now
                saved = {'thread': args.thread, 'snapshot': current, 'last_sent': now,
                         'last_events': events}
                atomic(monitor_state, saved)
                print(datetime.now(timezone.utc).isoformat(), 'Queued:', '; '.join(events), flush=True)
            atomic(folder / 'codex_monitor_health.json', {
                'pid': os.getpid(), 'checked_at': now, 'last_sent': last_sent,
                'status': 'complete' if current['complete'] else 'watching',
                'expires_at': now + max(0, deadline - time.monotonic())})
            if current['complete']:
                return
        except (OSError, ValueError, RuntimeError, subprocess.TimeoutExpired) as error:
            # Keep the watcher alive. Queue failures never change the acknowledged
            # snapshot, so an undelivered transition can be retried next cycle.
            print(datetime.now(timezone.utc).isoformat(), type(error).__name__, str(error), flush=True)
            atomic(folder / 'codex_monitor_health.json', {
                'pid': os.getpid(), 'checked_at': now, 'last_sent': last_sent,
                'status': 'retry_pending', 'error_type': type(error).__name__})
        time.sleep(args.interval)
    print('Monitor duration reached; no remote jobs were stopped.', flush=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--codex', type=Path, required=True)
    parser.add_argument('--thread', required=True)
    parser.add_argument('--interval', type=int, default=60)
    parser.add_argument('--health-seconds', type=int, default=900)
    parser.add_argument('--hours', type=float, default=24)
    args = parser.parse_args()
    if args.interval < 30 or args.health_seconds < 300 or not 0 < args.hours <= 48:
        parser.error('Use interval >=30s, health check >=300s, and duration (0,48] hours')
    run(args)
